#--------------------------
# server
#--------------------------
server:
  shutdown: graceful  # graceful shutdown 적용
  servlet:
    encoding:
      charset: utf-8
      force: true

#--------------------------
# spring
#--------------------------
spring:
  application:
    name: EcoAndRich
  profiles:
    active: local
  banner:
    charset: UTF-8
    location: "classpath:config/app-banner.txt"
  lifecycle:
    timeout-per-shutdown-phase: 35s # graceful shutdown 유예시간 설정 (default 30s)
#--------------------------
# swagger info
#--------------------------
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**
