apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoandrich-deployment
  labels:
    app: echoandrich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoandrich
  template:
    metadata:
      labels:
        app: echoandrich
    spec:
      containers:
        - name: echoandrichcontainer
          image: mirrorkyh/echoandrich:8081
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://ec2-3-37-17-244.ap-northeast-2.compute.amazonaws.com:3306/echonrich
            - name: SPRING_DATASOURCE_USERNAME
              value: echo2879
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: echoandrich-service
spec:
  selector:
    app: echoandrich
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30403
  type: NodePort
